# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
